db:
  host: localhost
  port: 5432
  dbName: anileha
  username: postgres
  password: postgres
rest:
  port: 3000
data:
  dir: data
conversion:
  parallelism: 1
  prefAudioLang: jpn
  prefSubLang: eng
  wordsPath: words.txt