db:
  host: localhost
  port: 5432
  dbName: anileha
  username: postgres
  password: postgres
rest:
  port: 8080
  baseUrl: http://127.0.0.1:8080
ws:
  writeTimeoutMs: 10000
  pingTimeoutMs: 30000
  pingIntervalMs: 20000
  maxMessageSize: 1024
  bufferSize: 1024
  messageChanBufferSize: 256
data:
  dir: data
thumb:
  attempts: 5
user:
  salt: salt
  cookieHashKey: qwertyuiopasdfghjkl;'zxcvbnm,.qw
  cookieEncryptKey: qwertyuiopasdfgh
admin:
  username: admin
  password: admin
mail:
  server: your.smtp.server
  port: 1337
  from: your@email.com
  username: user
  password: pass
  subject: AniLeha registration
  registerTemplatePath: register.tmpl